---
- name: Wait for port 22 to be ready
  hosts: '{{ instance_name }}'
  gather_facts: False
  tasks:
    - local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=10

- name: Create user account
  hosts: '{{ instance_name }}'
  become: yes
  gather_facts: false
  remote_user: "{{ ssh_user }}"

  tasks:
  - import_role:
      name: osp-add-user
    tags: ['user']
